// COMENTÁRIO DE UMA LINHA
    console.log("Linha 1");

/*
COMENTÁRIO DE 
MULTIPLAS LINHAS
*/    
    console.log("Linha 2");


// DICAS SOBRE OS COMENTÁRIOS
//  - EVITE COMENTÁRIOS OBVIOS 
//  - PREFIRA CÓDIGO LIMPO SEM MUITOS COMENTÁRIOS   